### ISSUE TITLE
Tech Writing Roadmap

### ISSUE THREAD

**Issue by phanhoang1366** [phanhoang1366/todo-homework#6]
- [x] Có 1 structure ổn
    - [x] 4-point và 10 point
    - [x] Đề xuất structure khác?
- [x] Research (và tìm thêm nguồn tài liệu nếu có)
- [x] Viết text, bảng, figures nếu có
- [x] Đọc lại text, criticize mạnh
- [x] In ra và chỉnh lý thêm 1 lần
